name: linux(gcc)

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get install libboost-all-dev
          sudo apt-get install lcov
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_COVERAGE=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Generate coverage reports
        working-directory: ${{github.workspace}}
        run: |
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '*/test/*' '*/include/utils/*' '*/src/utils/*' --output-file coverage.info

      - name: Upload reports to codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov 
          ./codecov -t ${CODECOV_TOKEN}
      
